# Generated by Django 3.1.1 on 2021-05-19 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='legend',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legends.legend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'legend', 'value')},
            },
        ),
    ]
