# Generated by Django 3.1.1 on 2021-05-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='artist',
            new_name='writer',
        ),
    ]
