# Generated by Django 3.1.1 on 2021-05-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='proposer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to='auth.user'),
            preserve_default=False,
        ),
    ]
