# Generated by Django 3.1.1 on 2021-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='description',
            field=models.TextField(default='Msanii'),
        ),
    ]
