# Generated by Django 3.1.1 on 2021-05-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_writerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprofile',
            name='county',
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
