# Generated by Django 3.1.1 on 2021-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210517_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='description',
            field=models.TextField(help_text='A brief biography of yourself.'),
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='writerprofile',
            name='description',
            field=models.TextField(help_text='A brief biography of yourself.'),
        ),
    ]
