# Generated by Django 3.1.1 on 2021-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
